version: '3.5'

services:
  postgres:
    container_name: pg_raiff
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: raiff
    ports:
      - "5433:5432"
    restart: always