spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/raif
    username: postgres
    password: 123321
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db-changelog-master.yaml
    enabled: true
server:
  port: 8080